### ISSUE TITLE
Release an alpha or beta version

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/guard-asciidoc#7]
Release an alpha or beta version of this plugin. It's being used by enough people that we know it's at least worth releasing at this point.

**Comment by teleivo** [comment]
any news on the release? a release would be great :+1:

**Comment by mojavelinux** [comment]
I recommend using https://rubygems.org/gems/guard-asciidoctor for now. That will eventually be folded into this plugin. I just haven't gotten to it  yet.

**Comment by teleivo** [comment]
thanks @mojavelinux I am using the suggested gem. However, the following Guardfile
```ruby
guard :asciidoctor do
  watch(/^.+(\.asciidoc)$/)
  watch(/^.+(\.adoc)$/)
end
```
does produce an html using the default asciidoctor/data/stylesheets/asciidoctor-default.css stylesheet whereas when I run
```bash
asciidoctor index.adoc
```
from the command line I get the html in format defined in the default stylesheet.

Do you have any hint for me?

Thanks a lot!

**Comment by mojavelinux** [comment]
Guard::AsciiDoc is born! See https://rubygems.org/gems/guard-asciidoc

Please note that guard-asciidoctor is now considered to be an unofficial fork. However, I would very much welcome an improvement to the tests in guard-asciidoc, so I'm prepared to accept some of those back into this upstream project.
